name: "URLcheck"
author: "Ayoub Malek"
description: "Automatically check for broken links in a project files. This includes python, markdwon, restructured text files and more."

inputs:
  base_path:
    description: "The project base path."
    required: True
  file_types:
    description: "A comma-separated list of file types to cover in the URL checks"
    required: False
    default: ".md,.py,.rst"
  print_all:
    description: "Choose whether to include file with no URLs in the prints."
    required: False
    default: False

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "link"
  color: "green"
